spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: basic
          uri: lb://basic
          predicates:
            - Path=/**
        - id: authorize
          uri: lb://authorize
          predicates:
            - Path=/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: /authorize/rsa/publicKey
