spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: basic
          uri: lb://basic
          predicates:
            - Path=/**