springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: trace
    org.springframework.security.web.access.expression: INFO
    org.shanzhaozhen: DEBUG