spring:
  profiles:
    active: dev

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
#        - id: nacos-route
#          uri: lb://service-gateway-provider
#          predicates:
#            - Path=/nacos/**
#          filters:
#            - StripPrefix=1
        - id: authorize
          uri: lb://authorize
          predicates:
            - Path=/authorize/**
        - id: uaa
          uri: lb://uaa
          predicates:
            - Path=/uaa/**
        - id: oauth
          uri: lb://oauth/**
          predicates:
            - Path=/oauth/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks    #配置RSA的公钥访问地址

springdoc:
  version: '0.0.1'
  title: '网关'
  description: '网关 API 文档 v0.0.1'
  swagger-ui:
    enabled: false
#    urls:
#      - name: uaa
#        url: /v3/api-docs/uaa
