springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: trace
    org.springframework.security.web.access.expression: INFO
    org.shanzhaozhen: DEBUG

  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 192.168.56.10
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password: 123456