spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: nacos-route
          uri: lb://service-gateway-provider
          predicates:
            - Path=/nacos/**
          filters:
            - StripPrefix=1
        - id: basic
          uri: lb://basic
          predicates:
            - Path=/basic/**
        - id: authorize
          uri: lb://authorize
          predicates:
            - Path=/authorize/**
        - id: security
          uri: lb://security
          predicates:
            - Path=/security/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server:9000/authorize/rsa/publicKey

  ## Redis 配置
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password: 123456
