server:
  port: 18080
  servlet:
#    session:
#      timeout:

spring:
  application:
    name: sentinel-example
  cloud:
    sentinel:
      transport:
        dashboard: 'localhost:18080'

sentinel:
  dashboard:
    auth:
      username: sentinel
      password: sentinel

