server:
  port: 9000

spring:
#  datasource:
#    url: jdbc:mysql://192.168.56.10:3306/authorize?useSSL=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    schema: classpath:best.sql
  ## Redis 配置
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 192.168.56.10
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password: 123456

# 第三方登陆配置
  security:
    oauth2:
      client:
        registration:
#          google-idp:
#            provider: google
#            client-id: ${GOOGLE_CLIENT_ID:google-client-id}
#            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
#            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
#            client-name: Sign in with Google
          github-idp:
            provider: github
            client-id: a7b9ba6f622f6e008c86
            client-secret: 2059cafb12c6b0e61df8cf57bec62c3d422c22c2
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
#          google:
#            user-name-attribute: email
          github:
            user-name-attribute: login

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印

## jwt配置
#jwt:
#  issuer: oldgod
#  secret: mySecret
#  #  header: Authorization
#  header: Best-Token
#  expiration: 3600
#  rememberExpiration: 604800

# jwt 配置
jwt:
  path: best-cloud.jks
  alias: best-cloud
  password: 123456

logging:
  level:
    root: INFO
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: trace
    org.springframework.security.web.access.expression: INFO
    org.shanzhaozhen: DEBUG