server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authorize?useSSL=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    schema: classpath:best.sql
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 192.168.56.10
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password: startlink

# jwt配置
#jwt:
#  issuer: oldgod
#  secret: mySecret
#  #  header: Authorization
#  header: Best-Token
#  expiration: 3600
#  rememberExpiration: 604800

# jks 配置
jwt:
  path: best-cloud.jks
  password: 123456
  alias: best-cloud

springdoc:
  api-docs:
    enabled: false

