#server:
#  servlet:
#    context-path: /basic-api

# 打包命令 mvn clean package -Dmaven.test.skip=true
spring:
  profiles:
    active: dev

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

